version: '3'
services:
  sonos-tannoy:
    container_name: sonos-tannoy
    image: larsim/sonos-tannoy:Dockerfile
    restart: unless-stopped
    privileged: true # Necessary for hid stuff
    network_mode: "host"
    volumes:
      - /dev/bus/usb /dev/bus/usb # for hid stuff
